package org.nicktorwald.adder

const val ENV_ADDER_SERVICE_KAFKA_CONNECT = "ADDER_SERVICE_KAFKA_CONNECT"
const val ENV_ADDER_SERVICE_MQ_IN_TOPIC = "ADDER_SERVICE_MQ_IN_TOPIC"
const val ENV_ADDER_SERVICE_MQ_OUT_TOPIC = "ADDER_SERVICE_MQ_OUT_TOPIC"
const val ENV_ADDER_SERVICE_REST_HOST = "ADDER_SERVICE_REST_HOST"
const val ENV_ADDER_SERVICE_REST_PORT = "ADDER_SERVICE_REST_PORT"
const val ENV_ADDER_SERVICE_MONGO_HOST = "ADDER_SERVICE_MONGO_HOST"
const val ENV_ADDER_SERVICE_MONGO_PORT = "ADDER_SERVICE_MONGO_PORT"
const val ENV_ADDER_SERVICE_LISTEN_PORT = "ADDER_SERVICE_LISTEN_PORT"
