package org.nicktorwald.mq

const val ENV_MQ_SERVICE_MQ_IN_TOPIC = "MQ_SERVICE_MQ_IN_TOPIC"
const val ENV_MQ_SERVICE_MQ_OUT_TOPIC = "MQ_SERVICE_MQ_OUT_TOPIC"
const val ENV_MQ_SERVICE_KAFKA_CONNECT = "MQ_SERVICE_KAFKA_CONNECT"
const val ENV_MQ_SERVICE_PROCESS_DELAY = "MQ_SERVICE_PROCESS_DELAY"
